report_authors:
  - Баранова Гиляна Басанговна
  - Другалев Александр Александрович
  - Конопельнюк Антон Петрович
  - Платонов Антон Александрович
  - Зимин Сергей Александрович
  - Попов Леонид Николаевич
